version: '4.5'
services:

  db:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - app-data-db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  backend:
    container_name: python
    depends_on:
      - db
    env_file:
      - .env
    ports: 
      - "8000:80"
    build: 
      context: ./backend
      dockerfile: Dockerfile

volumes:
  app-data-db: